In [1]:
import pandas as pd

In [2]:
# read 'IMDb movies.csv' and 'IMDb ratings.csv'
df_movies = pd.read_csv('IMDb movies.csv', low_memory=False)
df_ratings = pd.read_csv('IMDb ratings.csv')

In [3]:
df_movies.head()

,imdb_title_id,title,original_title,year,date_published,genre,duration,country,language,director,...,actors,description,avg_vote,votes,budget,usa_gross_income,worlwide_gross_income,metascore,reviews_from_users,reviews_from_critics
0,tt0000009,Miss Jerry,Miss Jerry,1894,1894-10-09,Romance,45,USA,NaN,Alexander Black,...,"Blanche Bayliss, William Courtenay, Chauncey D...",The adventures of a female reporter in the 1890s.,5.9,154,NaN,NaN,NaN,NaN,1.0,2.0
1,tt0000574,The Story of the Kelly Gang,The Story of the Kelly Gang,1906,1906-12-26,"Biography, Crime, Drama",70,Australia,NaN,Charles Tait,...,"Elizabeth Tait, John Tait, Norman Campbell, Be...",True story of notorious Australian outlaw Ned ...,6.1,589,$ 2250,NaN,NaN,NaN,7.0,7.0
2,tt0001892,Den sorte drøm,Den sorte drøm,1911,1911-08-19,Drama,53,"Germany, Denmark",NaN,Urban Gad,...,"Asta Nielsen, Valdemar Psilander, Gunnar Helse...",Two men of high rank are both wooing the beaut...,5.8,188,NaN,NaN,NaN,NaN,5.0,2.0
3,tt0002101,Cleopatra,Cleopatra,1912,1912-11-13,"Drama, History",100,USA,English,Charles L. Gaskill,...,"Helen Gardner, Pearl Sindelar, Miss Fielding, ...",The fabled queen of Egypt's affair with Roman ...,5.2,446,$ 45000,NaN,NaN,NaN,25.0,3.0
4,tt0002130,L'Inferno,L'Inferno,1911,1911-03-06,"Adventure, Drama, Fantasy",68,Italy,Italian,"Francesco Bertolini, Adolfo Padovan",...,"Salvatore Papa, Arturo Pirovano, Giuseppe de L...",Loosely adapted from Dante's Divine Comedy and...,7.0,2237,NaN,NaN,NaN,NaN,31.0,14.0

In [4]:
df_ratings.head()

,imdb_title_id,weighted_average_vote,total_votes,mean_vote,median_vote,votes_10,votes_9,votes_8,votes_7,votes_6,...,females_30age_avg_vote,females_30age_votes,females_45age_avg_vote,females_45age_votes,top1000_voters_rating,top1000_voters_votes,us_voters_rating,us_voters_votes,non_us_voters_rating,non_us_voters_votes
0,tt0000009,5.9,154,5.9,6.0,12,4,10,43,28,...,5.7,13.0,4.5,4.0,5.7,34.0,6.4,51.0,6.0,70.0
1,tt0000574,6.1,589,6.3,6.0,57,18,58,137,139,...,6.2,23.0,6.6,14.0,6.4,66.0,6.0,96.0,6.2,331.0
2,tt0001892,5.8,188,6.0,6.0,6,6,17,44,52,...,5.8,4.0,6.8,7.0,5.4,32.0,6.2,31.0,5.9,123.0
3,tt0002101,5.2,446,5.3,5.0,15,8,16,62,98,...,5.5,14.0,6.1,21.0,4.9,57.0,5.5,207.0,4.7,105.0
4,tt0002130,7.0,2237,6.9,7.0,210,225,436,641,344,...,7.3,82.0,7.4,77.0,6.9,139.0,7.0,488.0,7.0,1166.0

In [5]:
# select columns
df_movies = df_movies[['imdb_title_id', 'title', 'year',
                       'genre', 'country']]

df_ratings = df_ratings[['imdb_title_id', 'total_votes', 'mean_vote']]

In [6]:
df_movies.head()

,imdb_title_id,title,year,genre,country
0,tt0000009,Miss Jerry,1894,Romance,USA
1,tt0000574,The Story of the Kelly Gang,1906,"Biography, Crime, Drama",Australia
2,tt0001892,Den sorte drøm,1911,Drama,"Germany, Denmark"
3,tt0002101,Cleopatra,1912,"Drama, History",USA
4,tt0002130,L'Inferno,1911,"Adventure, Drama, Fantasy",Italy

In [7]:
df_ratings.head()

  imdb_title_id  total_votes  mean_vote
0     tt0000009          154        5.9
1     tt0000574          589        6.3
2     tt0001892          188        6.0
3     tt0002101          446        5.3
4     tt0002130         2237        6.9

# merge()

## Inner join

In [8]:
# merge df_movies and df_ratings (inner join)
df_movies.merge(df_ratings, on='imdb_title_id')

,imdb_title_id,title,year,genre,country,total_votes,mean_vote
0,tt0000009,Miss Jerry,1894,Romance,USA,154,5.9
1,tt0000574,The Story of the Kelly Gang,1906,"Biography, Crime, Drama",Australia,589,6.3
2,tt0001892,Den sorte drøm,1911,Drama,"Germany, Denmark",188,6.0
3,tt0002101,Cleopatra,1912,"Drama, History",USA,446,5.3
4,tt0002130,L'Inferno,1911,"Adventure, Drama, Fantasy",Italy,2237,6.9
...,...,...,...,...,...,...,...
85850,tt9908390,Le lion,2020,Comedy,"France, Belgium",398,5.5
85851,tt9911196,De Beentjes van Sint-Hildegard,2020,"Comedy, Drama",Netherlands,724,7.9
85852,tt9911774,Padmavyuhathile Abhimanyu,2019,Drama,India,265,7.8
85853,tt9914286,Sokagin Çocuklari,2019,"Drama, Family",Turkey,194,9.4
85854,tt9914942,La vida sense la Sara Amat,2019,Drama,Spain,102,6.8

## Outer join (Full join)

In [9]:
# merge df_movies and df_ratings (outer join)
df_movies.merge(df_ratings, on='imdb_title_id', how='outer')

,imdb_title_id,title,year,genre,country,total_votes,mean_vote
0,tt0000009,Miss Jerry,1894,Romance,USA,154,5.9
1,tt0000574,The Story of the Kelly Gang,1906,"Biography, Crime, Drama",Australia,589,6.3
2,tt0001892,Den sorte drøm,1911,Drama,"Germany, Denmark",188,6.0
3,tt0002101,Cleopatra,1912,"Drama, History",USA,446,5.3
4,tt0002130,L'Inferno,1911,"Adventure, Drama, Fantasy",Italy,2237,6.9
...,...,...,...,...,...,...,...
85850,tt9908390,Le lion,2020,Comedy,"France, Belgium",398,5.5
85851,tt9911196,De Beentjes van Sint-Hildegard,2020,"Comedy, Drama",Netherlands,724,7.9
85852,tt9911774,Padmavyuhathile Abhimanyu,2019,Drama,India,265,7.8
85853,tt9914286,Sokagin Çocuklari,2019,"Drama, Family",Turkey,194,9.4
85854,tt9914942,La vida sense la Sara Amat,2019,Drama,Spain,102,6.8

## Exclusive Outer join (Exclusive Full join)

In [10]:
# merge df_movies and df_ratings (Exclusive Full join)
df_movies.merge(df_ratings, on='imdb_title_id', how='outer', 
                indicator=True).query("_merge=='left_only' or _merge=='right_only'")

Empty DataFrame
Columns: [imdb_title_id, title, year, genre, country, total_votes, mean_vote, _merge]
Index: []

##  Left join

In [11]:
# extract a 50% sample of the df_movies dataframe
df_movies_sample = df_movies.sample(frac=0.5)

In [12]:
df_movies_sample

,imdb_title_id,title,year,genre,country
19874,tt0082317,Eles Não Usam Black-Tie,1981,Drama,Brazil
69839,tt3104078,WNUF Halloween Special,2013,"Comedy, Horror",USA
15942,tt0069863,Chabelo y Pepito contra los monstruos,1973,"Family, Horror, Comedy",Mexico
15296,tt0067981,Who Killed Mary Whats'ername?,1971,"Crime, Mystery",USA
10369,tt0053996,Storia di un disertore,1960,Drama,"West Germany, France"
...,...,...,...,...,...
71463,tt3495030,Dum Laga Ke Haisha,2015,"Comedy, Drama, Romance",India
31674,tt0124298,Sbucato dal passato,1999,"Comedy, Drama, Romance",USA
54934,tt1172991,The Company Men,2010,Drama,USA
1765,tt0024939,By Your Leave,1934,Comedy,USA
1843,tt0025273,Housewife,1934,Drama,USA

In [13]:
# merge df_movies_sample and df_ratings (left join)
df_left = df_movies_sample.merge(df_ratings, on='imdb_title_id',
                                 how='left')

In [14]:
df_left

,imdb_title_id,title,year,genre,country,total_votes,mean_vote
0,tt0082317,Eles Não Usam Black-Tie,1981,Drama,Brazil,1107,8.0
1,tt3104078,WNUF Halloween Special,2013,"Comedy, Horror",USA,780,6.7
2,tt0069863,Chabelo y Pepito contra los monstruos,1973,"Family, Horror, Comedy",Mexico,136,6.4
3,tt0067981,Who Killed Mary Whats'ername?,1971,"Crime, Mystery",USA,167,6.6
4,tt0053996,Storia di un disertore,1960,Drama,"West Germany, France",112,7.3
...,...,...,...,...,...,...,...
42923,tt3495030,Dum Laga Ke Haisha,2015,"Comedy, Drama, Romance",India,17508,7.7
42924,tt0124298,Sbucato dal passato,1999,"Comedy, Drama, Romance",USA,58563,6.8
42925,tt1172991,The Company Men,2010,Drama,USA,43078,6.8
42926,tt0024939,By Your Leave,1934,Comedy,USA,163,5.8
42927,tt0025273,Housewife,1934,Drama,USA,848,6.8

## Exclusive Left join

In [15]:
# make a copy of the df_movies dataframe
df_movies_2 = df_movies.copy()

In [16]:
df_movies_2

,imdb_title_id,title,year,genre,country
0,tt0000009,Miss Jerry,1894,Romance,USA
1,tt0000574,The Story of the Kelly Gang,1906,"Biography, Crime, Drama",Australia
2,tt0001892,Den sorte drøm,1911,Drama,"Germany, Denmark"
3,tt0002101,Cleopatra,1912,"Drama, History",USA
4,tt0002130,L'Inferno,1911,"Adventure, Drama, Fantasy",Italy
...,...,...,...,...,...
85850,tt9908390,Le lion,2020,Comedy,"France, Belgium"
85851,tt9911196,De Beentjes van Sint-Hildegard,2020,"Comedy, Drama",Netherlands
85852,tt9911774,Padmavyuhathile Abhimanyu,2019,Drama,India
85853,tt9914286,Sokagin Çocuklari,2019,"Drama, Family",Turkey
85854,tt9914942,La vida sense la Sara Amat,2019,Drama,Spain

In [17]:
# set the first 1000 values of 'imdb_title_id' column as 'tt1234567890'
for index in df_movies_2.index:
    if index < 1000:
        df_movies_2.loc[index, 'imdb_title_id'] = 'tt1234567890'

In [18]:
df_movies_2

,imdb_title_id,title,year,genre,country
0,tt1234567890,Miss Jerry,1894,Romance,USA
1,tt1234567890,The Story of the Kelly Gang,1906,"Biography, Crime, Drama",Australia
2,tt1234567890,Den sorte drøm,1911,Drama,"Germany, Denmark"
3,tt1234567890,Cleopatra,1912,"Drama, History",USA
4,tt1234567890,L'Inferno,1911,"Adventure, Drama, Fantasy",Italy
...,...,...,...,...,...
85850,tt9908390,Le lion,2020,Comedy,"France, Belgium"
85851,tt9911196,De Beentjes van Sint-Hildegard,2020,"Comedy, Drama",Netherlands
85852,tt9911774,Padmavyuhathile Abhimanyu,2019,Drama,India
85853,tt9914286,Sokagin Çocuklari,2019,"Drama, Family",Turkey
85854,tt9914942,La vida sense la Sara Amat,2019,Drama,Spain

In [19]:
# merge df_movies_2 and df_ratings (exclusive left join)
df_exclusive_left = df_movies_2.merge(df_ratings,
                                      on='imdb_title_id',
                                      how='outer', 
                                      indicator=True).query("_merge=='left_only'")

In [20]:
df_exclusive_left

,imdb_title_id,title,year,genre,country,total_votes,mean_vote,_merge
55817,tt1234567890,Miss Jerry,1894,Romance,USA,NaN,NaN,left_only
55818,tt1234567890,The Story of the Kelly Gang,1906,"Biography, Crime, Drama",Australia,NaN,NaN,left_only
55819,tt1234567890,Den sorte drøm,1911,Drama,"Germany, Denmark",NaN,NaN,left_only
55820,tt1234567890,Cleopatra,1912,"Drama, History",USA,NaN,NaN,left_only
55821,tt1234567890,L'Inferno,1911,"Adventure, Drama, Fantasy",Italy,NaN,NaN,left_only
...,...,...,...,...,...,...,...,...
56812,tt1234567890,Agente segreto Z1,1930,Drama,USA,NaN,NaN,left_only
56813,tt1234567890,Tom Sawyer,1930,"Adventure, Comedy, Drama",USA,NaN,NaN,left_only
56814,tt1234567890,Tonka Sibenice,1930,Drama,"Czechoslovakia, Germany",NaN,NaN,left_only
56815,tt1234567890,Top Speed,1930,"Comedy, Musical, Romance",USA,NaN,NaN,left_only
56816,tt1234567890,True to the Navy,1930,"Action, Comedy, Romance",USA,NaN,NaN,left_only

## Right join

In [21]:
# extract a 30% sample of the df_ratings dataframe
df_ratings_sample = df_ratings.sample(frac=0.3)

In [22]:
df_ratings_sample

      imdb_title_id  total_votes  mean_vote
53167     tt1054122         5133        7.0
47382     tt0453201         3690        7.6
34851     tt0180316          611        6.6
18959     tt0079285         8178        5.2
39376     tt0271263        21191        5.6
...             ...          ...        ...
45847     tt0417731          133        7.3
62568     tt1845211          554        4.5
56606     tt1295061          165        6.1
15496     tt0068564          206        6.1
29990     tt0117117          169        7.0

[25756 rows x 3 columns]

In [23]:
# merge df_movies and df_ratings_sample (right join)
df_right = df_movies.merge(df_ratings_sample, on='imdb_title_id',
                           how='right')

In [24]:
df_right

,imdb_title_id,title,year,genre,country,total_votes,mean_vote
0,tt1054122,Goemon,2009,"Action, Drama, History",Japan,5133,7.0
1,tt0453201,Sachein,2005,"Comedy, Drama, Romance",India,3690,7.6
2,tt0180316,Women Talking Dirty,1999,"Comedy, Romance",UK,611,6.6
3,tt0079285,Saturn 3,1980,"Adventure, Horror, Sci-Fi",UK,8178,5.2
4,tt0271263,Otto notti di follie,2002,"Animation, Comedy, Musical",USA,21191,5.6
...,...,...,...,...,...,...,...
25751,tt0417731,Guarding Eddy,2004,"Drama, Sport",USA,133,7.3
25752,tt1845211,Blooded,2011,"Horror, Thriller",UK,554,4.5
25753,tt1295061,Karla e Katrine Amiche Inseparabili,2009,Family,Denmark,165,6.1
25754,tt0068564,Face-Off,1971,"Drama, Romance, Sport",Canada,206,6.1
25755,tt0117117,My Mother's Courage,1995,"Drama, War","Germany, UK, Austria, Ireland",169,7.0

## Exclusive Right join

In [25]:
# make a copy of the df_ratings dataframe
df_ratings_2 = df_ratings.copy()

In [26]:
df_ratings_2

      imdb_title_id  total_votes  mean_vote
0         tt0000009          154        5.9
1         tt0000574          589        6.3
2         tt0001892          188        6.0
3         tt0002101          446        5.3
4         tt0002130         2237        6.9
...             ...          ...        ...
85850     tt9908390          398        5.5
85851     tt9911196          724        7.9
85852     tt9911774          265        7.8
85853     tt9914286          194        9.4
85854     tt9914942          102        6.8

[85855 rows x 3 columns]

In [27]:
# set the first 1000 values of 'imdb_title_id' column as 'tt1234567890'
for index in df_ratings_2.index:
    if index < 1000:
        df_ratings_2.loc[index, 'imdb_title_id'] = 'tt1234567890'

In [28]:
df_ratings_2

      imdb_title_id  total_votes  mean_vote
0      tt1234567890          154        5.9
1      tt1234567890          589        6.3
2      tt1234567890          188        6.0
3      tt1234567890          446        5.3
4      tt1234567890         2237        6.9
...             ...          ...        ...
85850     tt9908390          398        5.5
85851     tt9911196          724        7.9
85852     tt9911774          265        7.8
85853     tt9914286          194        9.4
85854     tt9914942          102        6.8

[85855 rows x 3 columns]

In [29]:
# merge df_movies and df_ratings_2 (exclusive right join)
df_exclusive_right = df_movies.merge(df_ratings_2,
                                     on='imdb_title_id',
                                     how='outer', 
                                     indicator=True).query("_merge=='right_only'")

In [30]:
df_exclusive_right

,imdb_title_id,title,year,genre,country,total_votes,mean_vote,_merge
55817,tt1234567890,NaN,NaN,NaN,NaN,154.0,5.9,right_only
55818,tt1234567890,NaN,NaN,NaN,NaN,589.0,6.3,right_only
55819,tt1234567890,NaN,NaN,NaN,NaN,188.0,6.0,right_only
55820,tt1234567890,NaN,NaN,NaN,NaN,446.0,5.3,right_only
55821,tt1234567890,NaN,NaN,NaN,NaN,2237.0,6.9,right_only
...,...,...,...,...,...,...,...,...
56812,tt1234567890,NaN,NaN,NaN,NaN,128.0,5.8,right_only
56813,tt1234567890,NaN,NaN,NaN,NaN,160.0,6.6,right_only
56814,tt1234567890,NaN,NaN,NaN,NaN,106.0,7.2,right_only
56815,tt1234567890,NaN,NaN,NaN,NaN,172.0,6.2,right_only
56816,tt1234567890,NaN,NaN,NaN,NaN,103.0,7.0,right_only